name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          components: clippy, rustfmt
      - run: cargo check
      - run: cargo run --help
      - run: cargo test
      - run: cargo fmt --all -- --check
      - run: cargo clippy
